### PR TITLE
Fixes dependency issues on Lumen 6

### PR DESCRIPTION
**Pull request by majidmvulle**
Fixes issue: https://github.com/dusterio/lumen-passport/issues/114

### CODE REVIEW

**Comment by dusterio** [comment]
@majidmvulle is this compatible with version 5 or do I have to make/tag a new version?

**Comment by majidmvulle** [comment]
@dusterio I'm currently doing tests with both 5 and 6. I will update you later today.

**Comment by EntrepreneurAJ** [comment]
@majidmvulle how did your tests go?

**Comment by majidmvulle** [comment]
Hi @EntrepreneurAJ @dusterio 
I have tested with Lumen 5.8. It works.

Here is the repo you can use to test locally as well.

https://github.com/majidmvulle/lumen-passport-test-5.8

**Comment by EntrepreneurAJ** [comment]
@dusterio confirmed his fork is running on 5.8.13 and 6.0.2

**Comment by lloricode** [comment]
> @majidmvulle is this compatible with version 5 or do I have to make/tag a new version?

@dusterio, this must running also on laravel 5, just add `compatibility` to **laravel 6** and remove laravel `deprecated functions`

**Comment by majidmvulle** [comment]
> Hi @EntrepreneurAJ @dusterio
> I have tested with Lumen 5.8. It works.
> 
> Here is the repo you can use to test locally as well.
> 
> https://github.com/majidmvulle/lumen-passport-test-5.8

Hey @lloricode please see this comment.

**Comment by lloricode** [comment]
> @dusterio confirmed his fork is running on 5.8.13 and 6.0.2

HI @majidmvulle its not laravel 6
https://github.com/majidmvulle/lumen-passport-test-5.8/blob/master/composer.json#L11

**Comment by majidmvulle** [comment]
> > @dusterio confirmed his fork is running on 5.8.13 and 6.0.2
> 
> HI @majidmvulle its not laravel 6
> https://github.com/majidmvulle/lumen-passport-test-5.8/blob/master/composer.json#L11

@lloricode this is to test backwards compatibility with 5. Lumen 6 works as I'm using it in an internal project. Do you want a repo to show that it works on 6?

**Comment by EntrepreneurAJ** [comment]
@lloricode I tested version 6 compatibility on a local instance replicating the code changes. the one in @majidmvulle is 5.8.13

**Comment by lloricode** [comment]
> > > @dusterio confirmed his fork is running on 5.8.13 and 6.0.2
> > 
> > 
> > HI @majidmvulle its not laravel 6
> > https://github.com/majidmvulle/lumen-passport-test-5.8/blob/master/composer.json#L11
> 
> @lloricode this is to test backwards compatibility with 5. Lumen 6 works as I'm using it in an internal project. Do you want a repo to show that it works on 6?

@majidmvulle sorry for misunderstanding, and the only problem is the testing

**Comment by lloricode** [comment]
looks good
https://travis-ci.org/dusterio/lumen-passport/jobs/587373728#L372
https://travis-ci.org/dusterio/lumen-passport/jobs/587373728#L372

how about this?
https://travis-ci.org/dusterio/lumen-passport/jobs/587373728#L422
https://travis-ci.org/dusterio/lumen-passport/jobs/587373729#L381

**Comment by lloricode** [comment]
maybe the problem is this https://github.com/dusterio/lumen-passport/pull/117/files#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780L24

**Pull request merged**
